/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WealthManagementRouteImport } from './routes/wealth-management'
import { Route as IndexRouteImport } from './routes/index'

const WealthManagementRoute = WealthManagementRouteImport.update({
  id: '/wealth-management',
  path: '/wealth-management',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wealth-management': typeof WealthManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wealth-management': typeof WealthManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wealth-management': typeof WealthManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wealth-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wealth-management'
  id: '__root__' | '/' | '/wealth-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WealthManagementRoute: typeof WealthManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wealth-management': {
      id: '/wealth-management'
      path: '/wealth-management'
      fullPath: '/wealth-management'
      preLoaderRoute: typeof WealthManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WealthManagementRoute: WealthManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
